# Generated by Django 6.0.6 on 2026-06-29 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_project_features_project_future_improvements_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectEnquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_type', models.CharField(choices=[('new_business_website', 'New business website'), ('website_redesign', 'Website redesign'), ('landing_page', 'Landing page'), ('portfolio_personal', 'Portfolio or personal website'), ('booking_enquiry_form', 'Website with booking/enquiry form'), ('product_catalogue', 'Product/catalogue website'), ('custom_web_app', 'Custom web application'), ('not_sure', 'Not sure yet')], max_length=80)),
                ('pages_needed', models.CharField(choices=[('one_page', '1 page'), ('two_four', '2-4 pages'), ('five_eight', '5-8 pages'), ('nine_plus', '9+ pages'), ('not_sure', 'Not sure')], max_length=40)),
                ('features', models.JSONField(blank=True, default=list)),
                ('content_status', models.JSONField(blank=True, default=list)),
                ('budget_range', models.CharField(blank=True, choices=[('under_300', 'Under GBP 300'), ('300_500', 'GBP 300-500'), ('500_1000', 'GBP 500-1,000'), ('1000_plus', 'GBP 1,000+'), ('not_sure', 'Not sure yet')], max_length=40)),
                ('timeframe', models.CharField(blank=True, choices=[('asap', 'ASAP'), ('one_two_weeks', '1-2 weeks'), ('two_four_weeks', '2-4 weeks'), ('flexible', 'Flexible')], max_length=40)),
                ('client_name', models.CharField(max_length=120)),
                ('business_name', models.CharField(blank=True, max_length=160)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('current_website', models.URLField(blank=True)),
                ('message', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('new', 'New'), ('reviewing', 'Reviewing'), ('contacted', 'Contacted'), ('quoted', 'Quoted'), ('won', 'Won'), ('lost', 'Lost'), ('spam', 'Spam')], default='new', max_length=20)),
                ('internal_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'project enquiries',
                'ordering': ['-created_at'],
            },
        ),
    ]
