# Generated by Django 6.0.6 on 2026-07-07 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_projectenquiry'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectEnquirySpamAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('honeypot', 'Honeypot filled'), ('too_fast', 'Submitted too quickly'), ('invalid_timestamp', 'Invalid timestamp')], max_length=40)),
                ('path', models.CharField(blank=True, max_length=240)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=300)),
                ('submitted_email', models.EmailField(blank=True, max_length=254)),
                ('submitted_name', models.CharField(blank=True, max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'blocked enquiry attempt',
                'verbose_name_plural': 'blocked enquiry attempts',
                'ordering': ['-created_at'],
            },
        ),
    ]
