# Generated by Django 6.0.6 on 2026-07-08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0005_projectenquiryspamattempt"),
    ]

    operations = [
        migrations.AddField(
            model_name="projectenquiry",
            name="next_action",
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.AddField(
            model_name="projectenquiry",
            name="next_follow_up_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
